"""empty message

Revision ID: 37da943c34f5
Revises: 92352e4e346f
Create Date: 2019-12-29 13:16:18.888108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da943c34f5'
down_revision = '92352e4e346f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupation', sa.Column('floor_3_perc', sa.Integer(), nullable=True))
    op.add_column('occupation', sa.Column('floor_4_perc', sa.Integer(), nullable=True))
    op.add_column('occupation', sa.Column('floor_5_perc', sa.Integer(), nullable=True))
    op.add_column('occupation', sa.Column('floor_6_perc', sa.Integer(), nullable=True))
    op.add_column('occupation', sa.Column('overall_occ', sa.Integer(), nullable=True))
    op.add_column('occupation', sa.Column('sum_of_people', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupation', 'sum_of_people')
    op.drop_column('occupation', 'overall_occ')
    op.drop_column('occupation', 'floor_6_perc')
    op.drop_column('occupation', 'floor_5_perc')
    op.drop_column('occupation', 'floor_4_perc')
    op.drop_column('occupation', 'floor_3_perc')
    # ### end Alembic commands ###
